// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mijqqvybmfgwvhxjdjib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1panFxdnlibWZnd3ZoeGpkamliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2Mzk0NTYsImV4cCI6MjA2OTIxNTQ1Nn0.aPv-oF-mYypHm6XVryQc5eYXrp0R0TZG0BayPs0-FyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});